// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Infrastructure.Migrations
{
    [DbContext(typeof(FinanceiroDbContext))]
    [Migration("20200623011209_mysql_Despeza")]
    partial class mysql_Despeza
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Entity.Entities.Base", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Bases");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Base");
                });

            modelBuilder.Entity("Entity.Entities.Categoria", b =>
                {
                    b.HasBaseType("Entity.Entities.Base");

                    b.Property<int>("IdSistema")
                        .HasColumnType("int");

                    b.HasIndex("IdSistema");

                    b.ToTable("Categoria");

                    b.HasDiscriminator().HasValue("Categoria");
                });

            modelBuilder.Entity("Entity.Entities.Compra", b =>
                {
                    b.HasBaseType("Entity.Entities.Base");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int");

                    b.HasIndex("IdCategoria");

                    b.ToTable("Compra");

                    b.HasDiscriminator().HasValue("Compra");
                });

            modelBuilder.Entity("Entity.Entities.Despesa", b =>
                {
                    b.HasBaseType("Entity.Entities.Base");

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnName("Despesa_DataAlteracao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnName("Despesa_DataCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataPagamento")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdCategoria")
                        .HasColumnName("Despesa_IdCategoria")
                        .HasColumnType("int");

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.Property<bool>("Pago")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("TipoDespesa")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(65,30)");

                    b.HasIndex("IdCategoria");

                    b.ToTable("Despesa");

                    b.HasDiscriminator().HasValue("Despesa");
                });

            modelBuilder.Entity("Entity.Entities.ItemCompra", b =>
                {
                    b.HasBaseType("Entity.Entities.Base");

                    b.Property<bool>("Comprado")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnName("ItemCompra_DataAlteracao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnName("ItemCompra_DataCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCompra")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdCompra")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnName("ItemCompra_Valor")
                        .HasColumnType("decimal(65,30)");

                    b.HasIndex("IdCompra");

                    b.ToTable("ItemCompra");

                    b.HasDiscriminator().HasValue("ItemCompra");
                });

            modelBuilder.Entity("Entity.Entities.SistemaFinanceiro", b =>
                {
                    b.HasBaseType("Entity.Entities.Base");

                    b.Property<int>("Ano")
                        .HasColumnName("SistemaFinanceiro_Ano")
                        .HasColumnType("int");

                    b.Property<int>("AnoCopia")
                        .HasColumnType("int");

                    b.Property<int>("DiaFechamento")
                        .HasColumnType("int");

                    b.Property<bool>("GerarCopiaDespesa")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Mes")
                        .HasColumnName("SistemaFinanceiro_Mes")
                        .HasColumnType("int");

                    b.Property<int>("MesCopia")
                        .HasColumnType("int");

                    b.ToTable("SistemaFinanceiro");

                    b.HasDiscriminator().HasValue("SistemaFinanceiro");
                });

            modelBuilder.Entity("Entity.Entities.Categoria", b =>
                {
                    b.HasOne("Entity.Entities.SistemaFinanceiro", "SistemaFinanceiro")
                        .WithMany()
                        .HasForeignKey("IdSistema")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entity.Entities.Compra", b =>
                {
                    b.HasOne("Entity.Entities.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entity.Entities.Despesa", b =>
                {
                    b.HasOne("Entity.Entities.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entity.Entities.ItemCompra", b =>
                {
                    b.HasOne("Entity.Entities.Compra", "Compra")
                        .WithMany()
                        .HasForeignKey("IdCompra")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
